//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIKHAB.Models.db
{

    public partial class BankaBilgileri
    {
        public int id { get; set; }
        public string Banka { get; set; }
        public string Iban { get; set; }
    }
}
