//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIKHAB.Models.db
{
    using System;

    public partial class IsBilgileri
    {
        public int id { get; set; }
        public int Is { get; set; }
        public int Yili { get; set; }
        public int FenKayitNo { get; set; }
        public Nullable<System.DateTime> FenKayitTarihi { get; set; }
        public string PaftaNo { get; set; }
        public string AdaNo { get; set; }
        public string ParselNo { get; set; }
        public string Takipci { get; set; }
        public string Maliki { get; set; }
        public string Aciklama { get; set; }
        public string Cinsi { get; set; }
        public string Ilgilenen { get; set; }
        public string FaturaNo { get; set; }
        public Nullable<System.DateTime> WhenUpdated { get; set; }
        public string WhoCreated { get; set; }
        public string WhoUpdated { get; set; }
        public Nullable<System.DateTime> WhenCreated { get; set; }
    
        public virtual Isler Isler { get; set; }
    }
}
