//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIKHAB.Models.db
{
    using System;
    using System.Collections.Generic;

    public partial class Isler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Isler()
        {
            this.IsAsamalari = new HashSet<IsAsamalari>();
            this.IsParametreleri = new HashSet<IsParametreleri>();
            this.Randevu = new HashSet<Randevu>();
            this.UcretDokumu = new HashSet<UcretDokumu>();
            this.IsBilgileri = new HashSet<IsBilgileri>();
        }
    
        public int id { get; set; }
        public int IsinCinsi { get; set; }
        public int Koyu_Mahallesi { get; set; }
        public Nullable<int> IsinTuru { get; set; }
        public Nullable<bool> KadastroyaAsliGibiVerilecek { get; set; }
        public Nullable<bool> Stopaj { get; set; }
        public Nullable<bool> Tevkifatli { get; set; }
        public Nullable<bool> KentselDonusum { get; set; }
        public Nullable<decimal> YolKilometre { get; set; }
        public Nullable<bool> YolUcretiniElleGir { get; set; }
        public int Musteri { get; set; }
        public string MusteriTemsilDurumu { get; set; }
        public string WhoCreated { get; set; }
        public string WhoUpdated { get; set; }
        public Nullable<System.DateTime> WhenCreated { get; set; }
        public Nullable<System.DateTime> WhenUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsAsamalari> IsAsamalari { get; set; }
        public virtual IsinCinsi IsinCinsi1 { get; set; }
        public virtual IsTurleri IsTurleri { get; set; }
        public virtual Koy_Mahalle Koy_Mahalle { get; set; }
        public virtual Musteri Musteri1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsParametreleri> IsParametreleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Randevu> Randevu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UcretDokumu> UcretDokumu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsBilgileri> IsBilgileri { get; set; }
    }
}
