//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIKHAB.Models.db
{
    using System;

    public partial class IsParametreleri
    {
        public int id { get; set; }
        public int Is { get; set; }
        public Nullable<decimal> YuzOlcumu { get; set; }
        public Nullable<int> AplikasyonKrokisiSayisi { get; set; }
        public Nullable<int> ParselSayisi { get; set; }
        public Nullable<int> NoktaSayisi { get; set; }
        public Nullable<decimal> ParselAlani { get; set; }
        public Nullable<decimal> BinaTabanAlani { get; set; }
        public Nullable<decimal> InsaatAlani { get; set; }
        public Nullable<int> BagimsizBolumSayisi { get; set; }
        public Nullable<int> BinaSayisi { get; set; }
        public Nullable<int> PlanOrnegi { get; set; }
        public Nullable<int> KatSayisi { get; set; }
        public Nullable<int> B_Bolum { get; set; }
        public Nullable<decimal> OdaKatsayi { get; set; }
        public Nullable<bool> AraziyeGidilecekmi { get; set; }
        public Nullable<bool> AyniKisiyeAit { get; set; }
        public Nullable<bool> OdaBirimFiyatlariniKullan { get; set; }
        public Nullable<bool> Yuzde50CarpanUygula { get; set; }
        public Nullable<decimal> YolUcreti { get; set; }
        public Nullable<System.DateTime> WhenUpdated { get; set; }
        public string WhoCreated { get; set; }
        public string WhoUpdated { get; set; }
        public Nullable<System.DateTime> WhenCreated { get; set; }
    
        public virtual Isler Isler { get; set; }
    }
}
