//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIKHAB.Models.db
{

    public partial class LisansliBuroBilgileri
    {
        public int id { get; set; }
        public string KimlikNo { get; set; }
        public string AdiSoyadi { get; set; }
        public string Unvani { get; set; }
        public string LisansliBuroNo { get; set; }
        public string LisansliBelgeNo { get; set; }
        public string OdaSicilNo { get; set; }
        public string VergiNo { get; set; }
        public string Ili { get; set; }
        public string Adresi { get; set; }
        public string Tel { get; set; }
        public string Faks { get; set; }
        public string Eposta { get; set; }
        public string Websayfasi { get; set; }
        public string VergiDairesi { get; set; }
        public string Ilcesi { get; set; }
    }
}
