//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIKHAB.Models.db
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class LIHKAB_dbEntities : DbContext
    {
        public LIHKAB_dbEntities()
            : base("name=LIHKAB_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ayarlar> Ayarlar { get; set; }
        public virtual DbSet<BankaBilgileri> BankaBilgileri { get; set; }
        public virtual DbSet<EmailKayitlari> EmailKayitlari { get; set; }
        public virtual DbSet<IsParametreleri> IsParametreleri { get; set; }
        public virtual DbSet<IsTurleri> IsTurleri { get; set; }
        public virtual DbSet<OnayTuru> OnayTuru { get; set; }
        public virtual DbSet<OnayTuruOnayVerecekKisi> OnayTuruOnayVerecekKisi { get; set; }
        public virtual DbSet<OnayVerecekKisi> OnayVerecekKisi { get; set; }
        public virtual DbSet<UcretAyarlari> UcretAyarlari { get; set; }
        public virtual DbSet<UcretDokumu> UcretDokumu { get; set; }
        public virtual DbSet<ViewIsinKucukDetayi> ViewIsinKucukDetayi { get; set; }
        public virtual DbSet<ViewRandevuTalebiReportDetail> ViewRandevuTalebiReportDetail { get; set; }
        public virtual DbSet<ViewRandevularIsBilgisiOlmayan> ViewRandevularIsBilgisiOlmayan { get; set; }
        public virtual DbSet<Onaylar> Onaylar { get; set; }
        public virtual DbSet<ViewRandevuOnayDurumu> ViewRandevuOnayDurumu { get; set; }
        public virtual DbSet<ViewRandevuGenelOnayDurumu> ViewRandevuGenelOnayDurumu { get; set; }
        public virtual DbSet<IsinCinsi> IsinCinsi { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRoles> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<View_IsAsamalari> View_IsAsamalari { get; set; }
        public virtual DbSet<IsAsamalari> IsAsamalari { get; set; }
        public virtual DbSet<ViewFenKayitSonrakiNumara> ViewFenKayitSonrakiNumara { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<Ilce> Ilce { get; set; }
        public virtual DbSet<Ili> Ili { get; set; }
        public virtual DbSet<Isler> Isler { get; set; }
        public virtual DbSet<Koy_Mahalle> Koy_Mahalle { get; set; }
        public virtual DbSet<MusteriTemsilDurumu> MusteriTemsilDurumu { get; set; }
        public virtual DbSet<Randevu> Randevu { get; set; }
        public virtual DbSet<RandevuIlkHali> RandevuIlkHali { get; set; }
        public virtual DbSet<View_RaporSozlesme> View_RaporSozlesme { get; set; }
        public virtual DbSet<IsBilgileri> IsBilgileri { get; set; }
        public virtual DbSet<LisansliBuroBilgileri> LisansliBuroBilgileri { get; set; }
        public virtual DbSet<ViewTeslimSenedi> ViewTeslimSenedi { get; set; }
    }
}
