//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIKHAB.Models.db
{
    using System;

    public partial class Onaylar
    {
        public int id { get; set; }
        public int OnayKodu { get; set; }
        public string UserId { get; set; }
        public int OnaylananSatirId { get; set; }
        public Nullable<System.DateTime> OnayZamani { get; set; }
    
        public virtual OnayTuruOnayVerecekKisi OnayTuruOnayVerecekKisi { get; set; }
    }
}
