//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIKHAB.Models.db
{
    using System.Collections.Generic;

    public partial class OnayTuruOnayVerecekKisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OnayTuruOnayVerecekKisi()
        {
            this.Onaylar = new HashSet<Onaylar>();
        }
    
        public int OnayKodu { get; set; }
        public string OnayVerecekUserId { get; set; }
    
        public virtual OnayTuru OnayTuru { get; set; }
        public virtual OnayVerecekKisi OnayVerecekKisi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Onaylar> Onaylar { get; set; }
    }
}
