//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIKHAB.Models.db
{

    public partial class UcretAyarlari
    {
        public int id { get; set; }
        public string IsDetayi { get; set; }
        public string UcretKodu { get; set; }
        public string Aciklama { get; set; }
        public bool Kullan { get; set; }
        public decimal Parametre { get; set; }
    }
}
