//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIKHAB.Models.db
{
    using System;

    public partial class UcretDokumu
    {
        public int id { get; set; }
        public Nullable<int> Is { get; set; }
        public Nullable<decimal> YolUcreti { get; set; }
        public Nullable<decimal> DenetimUcreti { get; set; }
        public Nullable<decimal> DamgaVergisi { get; set; }
        public Nullable<decimal> BelgeUcreti { get; set; }
        public Nullable<decimal> KontrolUcreti { get; set; }
        public Nullable<decimal> Toplam { get; set; }
        public Nullable<decimal> ToplamBrutUcret { get; set; }
        public Nullable<decimal> Stopaj20percent { get; set; }
        public Nullable<decimal> KesintilerToplami { get; set; }
        public Nullable<decimal> GenelToplam { get; set; }
        public Nullable<decimal> KDV18percent { get; set; }
        public Nullable<decimal> TevkifEdilenKDV { get; set; }
        public Nullable<decimal> TahsilEdilenKDV { get; set; }
        public Nullable<decimal> NetAlinan { get; set; }
        public Nullable<decimal> AlinacakGenelToplam { get; set; }
        public Nullable<System.DateTime> WhenUpdated { get; set; }
        public string WhoCreated { get; set; }
        public string WhoUpdated { get; set; }
        public Nullable<System.DateTime> WhenCreated { get; set; }
    
        public virtual Isler Isler { get; set; }
    }
}
