//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIKHAB.Models.db
{
    using System;

    public partial class ViewRandevuGenelOnayDurumu
    {
        public int RandevuId { get; set; }
        public Nullable<int> GerekenOnaySayisi { get; set; }
        public int OnaySayisi { get; set; }
        public int Onaylanmis { get; set; }
    }
}
