//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIKHAB.Models.db
{

    public partial class ViewTeslimSenedi
    {
        public int isId { get; set; }
        public string Cinsi { get; set; }
        public string Koy_Mahalle { get; set; }
        public string PaftaNo { get; set; }
        public string AdaNo { get; set; }
        public string ParselNo { get; set; }
        public string YuzOlcumu { get; set; }
        public string Tanim { get; set; }
        public string FenKayitTarihi { get; set; }
        public string FenKayitTarihiGUN { get; set; }
        public string FenKayitTarihiAY { get; set; }
        public string FenKayitTarihiYIL { get; set; }
        public string LisansliBuroSahibi { get; set; }
        public string LisansliBuroSahibiUnvani { get; set; }
        public string isSahibi { get; set; }
        public string BirimFiyati { get; set; }
        public string ToplamFiyat { get; set; }
    }
}
