//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIKHAB.Models.db
{
    using System;

    public partial class ViewRandevuTalebiReportDetail
    {
        public System.Guid UniqueId { get; set; }
        public string Tanim { get; set; }
        public string AdiSoyadi { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Koy_Mahalle { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Description { get; set; }
        public int isId { get; set; }
        public int RandevuId { get; set; }
        public string IsiOlusturan { get; set; }
        public string RandevuyuVeren { get; set; }
    }
}
