//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIKHAB.Models.db
{
    using System;

    public partial class ViewFenKayitSonrakiNumara
    {
        public System.Guid UniqueId { get; set; }
        public int Yil { get; set; }
        public int IlceId { get; set; }
        public Nullable<int> VerilecekFenKayitNo { get; set; }
    }
}
