//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIKHAB.Models.db
{
    using System;

    public partial class View_IsAsamalari
    {
        public System.Guid UniqueId { get; set; }
        public int id { get; set; }
        public int IsId { get; set; }
        public Nullable<System.DateTime> OnayaGidisZamani { get; set; }
        public bool Onaylanmis { get; set; }
        public Nullable<System.DateTime> OnayZamani { get; set; }
        public Nullable<bool> Randevu { get; set; }
        public Nullable<System.DateTime> RandevuWhen { get; set; }
        public bool Fatura { get; set; }
        public Nullable<System.DateTime> FaturaWhen { get; set; }
        public bool Olcum { get; set; }
        public Nullable<System.DateTime> OlcumWhen { get; set; }
        public bool Kontrol { get; set; }
        public Nullable<System.DateTime> KontrolWhen { get; set; }
        public bool BeldEvrGeldi { get; set; }
        public Nullable<System.DateTime> BeldEvrGeldiWhen { get; set; }
        public bool BeldEvrGitti { get; set; }
        public Nullable<System.DateTime> BeldEvrGittiWhen { get; set; }
        public bool KadEvrGeldi { get; set; }
        public Nullable<System.DateTime> KadEvrGeldiWhen { get; set; }
        public bool KadEvrGitti { get; set; }
        public Nullable<System.DateTime> KadEvrGittiWhen { get; set; }
        public bool ProjeYapildi { get; set; }
        public Nullable<System.DateTime> ProjeYapildiWhen { get; set; }
        public bool OdemeAlindi { get; set; }
        public Nullable<System.DateTime> OdemeAlindiWhen { get; set; }
        public bool IsKapandi { get; set; }
        public Nullable<System.DateTime> IsKapandiWhen { get; set; }
        public string WhoCreated { get; set; }
        public string WhoUpdated { get; set; }
        public Nullable<System.DateTime> WhenCreated { get; set; }
        public Nullable<System.DateTime> WhenUpdated { get; set; }
        public bool MusteriyiBilgilendir { get; set; }
        public Nullable<System.DateTime> MusteriyiBilgilendirWhen { get; set; }
    }
}
