//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIKHAB.Models.db
{

    public partial class View_RaporSozlesme
    {
        public int IsId { get; set; }
        public string IlinAdi { get; set; }
        public string Ilce { get; set; }
        public string Koy_Mahalle { get; set; }
        public string IsSahibi { get; set; }
        public string IsSahibiVeUnvani { get; set; }
        public string MusteriTemsilDurumuIsler { get; set; }
        public string IsinCinsiTanim { get; set; }
        public string RandevuZamani { get; set; }
        public string Toplam { get; set; }
        public string KDV { get; set; }
        public string GenelToplam { get; set; }
        public string MalikiIBAdiSoyadi { get; set; }
        public string IsSahibiTCkimlik_VergiNo { get; set; }
        public string IsSahibiTelefon1 { get; set; }
        public string IsSahibiAdress { get; set; }
        public string LisansSahibi_AdiSoyadi { get; set; }
        public string LisansliBuroNo { get; set; }
        public string LisansliBelgeNo { get; set; }
        public string OdaSicilNo { get; set; }
        public string LisansSahibiIli { get; set; }
        public string AdaParselNo { get; set; }
        public string PaftaNo { get; set; }
        public string FenKayitTarihiNo { get; set; }
        public string FenKayitTarihi { get; set; }
        public string FenKayitTarihiGUN { get; set; }
        public string FenKayitTarihiAY { get; set; }
        public string FenKayitTarihiYIL { get; set; }
        public string Yuzolcumu { get; set; }
        public int IsinCinsiId { get; set; }
    }
}
