//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIKHAB.Models.db
{
    using System;

    public partial class ViewRandevuOnayDurumu
    {
        public long UniqueId { get; set; }
        public int RandevuId { get; set; }
        public Nullable<int> OnayId { get; set; }
        public int OnayKodu { get; set; }
        public string OnayVerecekUserId { get; set; }
        public string UserName { get; set; }
        public string AdiSoyadi { get; set; }
        public Nullable<System.DateTime> OnayZamani { get; set; }
    }
}
