// <auto-generated />
namespace LIKHAB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AdiSoyadi2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdiSoyadi2));
        
        string IMigrationMetadata.Id
        {
            get { return "201803062238549_AdiSoyadi2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
